services:
  backend:
    build:
      context: .
      dockerfile: docker-prod/backend/Dockerfile.symfony
    environment:
      APP_ENV: prod
      # Si tu veux tester la DB locale (mêmes valeurs que ton dev):
      DATABASE_URL: "mysql://root:YourPassword123@database:3306/GreenITScan?charset=utf8mb4"
    depends_on:
      - database
    ports:
      - "8081:8080"

  frontend:
    build:
      context: .
      dockerfile: docker-prod/frontend/Dockerfile.frontend
    environment:
      # En prod.local, front → back via port local
      API_URL: "http://localhost:8081/api"
    ports:
      - "8080:80"

  database:
    image: mariadb:11.8.2
    environment:
      MYSQL_ROOT_PASSWORD: "YourPassword123"
      MYSQL_DATABASE: "GreenITScan"
    ports:
      - "3307:3306"
    volumes:
      - GreenITScan_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-pYourPassword123"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  GreenITScan_mariadb_data:
