alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: yo-ikhelef-greenitscan-backend
      preserve_path_prefix: true
    match:
      authority: {}
      path:
        prefix: /api
  - component:
      name: yo-ikhelef-greenitscan-frontend
    match:
      authority: {}
      path:
        prefix: /
name: green-it-scan-app
region: fra
services:
- envs:
  - key: APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: prod
  - key: APP_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_PUBLIC_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_PASSPHRASE
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_PRIVATE_KEY_B64
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_PUBLIC_KEY_B64
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_ROOT_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_DATABASE
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: OWNER_LC
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: REPO_LC
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: BACK_TAG
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: FRONT_TAG
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  http_port: 8080
  image:
    registry: yo-ikhelef
    registry_type: GHCR
    repository: greenitscan/backend
    tag: branch-prod
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yo-ikhelef-greenitscan-backend
- http_port: 80
  image:
    registry: yo-ikhelef
    registry_type: GHCR
    repository: greenitscan/frontend
    tag: branch-prod
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yo-ikhelef-greenitscan-frontend
