alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: yo-ikhelef-greenitscan-backend
      preserve_path_prefix: true
    match:
      path:
        prefix: /api
  - component:
      name: yo-ikhelef-greenitscan-frontend
    match:
      path:
        prefix: /
name: green-it-scan-app
region: fra
envs:
  - key: APP_ENV
    value: prod
    scope: RUN_TIME
  - key: DATABASE_URL
    type: SECRET
    scope: RUN_TIME
  - key: APP_SECRET
    type: SECRET
    scope: RUN_TIME
  - key: JWT_SECRET_KEY
    type: SECRET
    scope: RUN_TIME
  - key: JWT_PUBLIC_KEY
    type: SECRET
    scope: RUN_TIME
  - key: JWT_PASSPHRASE
    type: SECRET
    scope: RUN_TIME
  - key: JWT_PRIVATE_KEY_B64
    type: SECRET
    scope: RUN_TIME
  - key: JWT_PUBLIC_KEY_B64
    type: SECRET
    scope: RUN_TIME
services:
- http_port: 8080
  image:
    registry: yo-ikhelef
    registry_type: GHCR
    repository: greenitscan/backend
    tag: branch-prod
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yo-ikhelef-greenitscan-backend
- http_port: 80
  image:
    registry: yo-ikhelef
    registry_type: GHCR
    repository: greenitscan/frontend
    tag: branch-prod
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yo-ikhelef-greenitscan-frontend
jobs:
  - name: migrations
    kind: PRE_DEPLOY
    image:
      registry: yo-ikhelef
      registry_type: GHCR
      repository: greenitscan/backend
      tag: branch-prod
    run_command: >
      sh -lc "php bin/console doctrine:migrations:migrate --no-interaction"
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
