name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["Build & Push images (GHCR)"]
    types: [completed]
  workflow_dispatch: {}

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Trigger redeploy with current spec (no spec file)
        run: doctl apps create-deployment ${{ secrets.DO_APP_ID }}