# # .github/workflows/deploy.yml
# name: Deploy to DigitalOcean App Platform

# on:
#   workflow_run:
#     workflows: ["Build & Push images (GHCR)"]
#     branches: [ prod ]
#     types: [ completed ]
#   workflow_dispatch: {}

# jobs:
#   deploy:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest
#     environment:
#       name: production      # -> utilise l'environnement GitHub "production"
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install doctl
#         uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DO_API_TOKEN }}
#       - name: Validate spec
#         run: doctl apps spec validate .do/app.yaml
#       - name: Update app from spec
#         run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml
