name: Deploy to DigitalOcean App Platform

on:
  workflow_run:
    workflows: ["Build & Push images (GHCR)"]
    types: [ completed ]
  workflow_dispatch: {}

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'prod'
      }}
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}   # 👈 clé : déploie le spec du commit mergé sur prod

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      # (debug utile) pour vérifier quel spec tu appliques réellement
      - name: Show spec we apply (masked)
        run: |
          echo "----- COMMIT: ${{ github.event.workflow_run.head_sha }}  BRANCH: ${{ github.event.workflow_run.head_branch }} -----"
          sed -e 's/DATABASE_URL:.*/DATABASE_URL: (hidden)/' .do/app.yaml

      - name: Validate spec
        run: doctl apps spec validate .do/app.yaml

      - name: Update app from spec (triggers a deployment)
        run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml

      - name: Fetch current remote spec
        run: doctl apps spec get ${{ secrets.DO_APP_ID }} > .do/app.remote.yaml

      - name: Diff remote vs local spec
        run: |
          echo "----- DIFF (remote vs local) -----"
          diff -u .do/app.remote.yaml .do/app.yaml || true
