name: Deploy to DigitalOcean App Platform

on:
  workflow_run:
    workflows: ["Build & Push images (GHCR)"]
    types: [ completed ]
  workflow_dispatch: {}

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'prod'
      }}
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}   # 👈 clé : déploie le spec du commit mergé sur prod

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Prepare spec pinned to this commit
        run: |
          SHA="${{ github.event.workflow_run.head_sha }}"
          SHORT="${SHA:0:7}"
          awk -v s="$SHORT" '
            $0 ~ "repository:.*greenitscan/backend" { print; getline; sub(/tag:.*/, "tag: sha-" s); print; next }
            $0 ~ "repository:.*greenitscan/frontend" { print; getline; sub(/tag:.*/, "tag: sha-" s); print; next }
            { print }
          ' .do/app.yaml > .do/app.override.yaml

      - name: Validate spec (override)
        run: doctl apps spec validate .do/app.override.yaml

      - name: Update app from spec (override)
        run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.override.yaml
