name: Build & Push images (GHCR)

on:
  push:
    branches: [ "testing-cicd-youri" ]          # adapte si besoin
    paths:
      - "docker-prod/**"
      - "api-backend/**"
      - "quasar-project/**"
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Backend
      - name: Build & push backend (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-prod/backend/Dockerfile.symfony
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/greenitscan/backend:${{ github.sha }}
            ghcr.io/${{ secrets.GHCR_USER }}/greenitscan/backend:prod
          platforms: linux/amd64
          cache-from: type=gha,scope=backend
          cache-to: type=gha,scope=backend,mode=max

      # Frontend
      - name: Build & push frontend (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-prod/frontend/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/greenitscan/frontend:${{ github.sha }}
            ghcr.io/${{ secrets.GHCR_USER }}/greenitscan/frontend:prod
          platforms: linux/amd64
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,scope=frontend,mode=max
